### ISSUE TITLE
Session timeout happened unexpectedly

### ISSUE THREAD

**Issue by reefdog** [PhilanthropyDataCommons/front-end#51]
Distinct from the general improvement around session timeout user experience in #50, this issue captures an incident that occurred to @kfogel while demoing #49 on its [Netlify deploy URL](https://deploy-preview-49--philanthropy-data-commons-viewer.netlify.app/).

Karl had opened several individual proposals in separate tabs and was scrolling through one of them when its page suddenly (without any apparent network-utilizing interaction, but ~10 minutes after login) went to the "Session timed out: Your session expired. Please re-authenticate." screen:

> Just now, while Justin was giving me a tour and I was logged in via my Firefox-on-desktop browser, suddenly my proposal tabs did a session timeout -- each proposal detail page just suddenly switched to a mostly blank page that said only "session timeout. your session has expired (etc)".
>
> Justin didn't know why that might be happening. So maybe it's a good idea to go grab & preserve some logs on the server right now, in case they help for reproduction? Or is is this a known thing that's about to get fixed?

@bickelj checked the auth container logs and saw many of these:

`2023-04-04 14:01:00,514 WARN [org.keycloak.events] (executor-thread-43) type=REFRESH_TOKEN_ERROR, realmId=8bb0740a-dceb-4f50-b447-174639011d2a, clientId=pdc-data-viewer, userId=null, ipAddress=[jesse redacted], error=invalid_token, grant_type=refresh_token, client_auth_method=client-secret`

I speculate this _may_ be a red herring due to the special-cased Netlify deploy URL (perhaps it was configured with an aggressively short timeout for security?) but we should look into it to be sure all is working as intended. Labeling as a bug in that spirit.

**Comment by bickelj** [comment]
The first instance should be captured in a range from T15:10Z to T15:40Z while the second instance from T16:00Z to around T16:20Z.

The auth log message above is from T14:01Z, outside the range of the periods of interest and I don't see any of those messages during the periods of interest.

I also do not see very many HTTP status 401 responses from the back-end web service (e.g. due to invalid or expired token). The 401s I do see are from the API docs front-end, not from the data-viewer front-end. I think this rules out the back-end web service as having the issue. The lack of 401s from the web service indicates that perhaps the front-end data viewer is not attempting to make the call. There do not appear to be any errors in the auth service logs for the periods of interest either. It is likely something in or between the data-viewer and the auth service, then.

**Comment by bickelj** [comment]
The Keycloak interface suggests that the session has been going from T15:07Z onward, so that's interesting:

![auth_session_screenshot_20230404T1130](https://user-images.githubusercontent.com/8806433/229858561-5fba0d04-98cd-44af-a9cf-668ba3a79e75.png)

**Comment by bickelj** [comment]
In summary, my best guess for now is this: it doesn't look like the session actually expired, but the data-viewer or its OIDC library seems to think it has expired.

**Comment by jasonaowen** [comment]
> Karl had opened several individual proposals in separate tabs

Thank you for including this very important bit of information!

This appears to be a multi-tab issue that I was able to reproduce, minimize, and add to the [existing upstream issue](https://github.com/AxaFrance/react-oidc/issues/1021).

For now, the work-around is not to use multiple tabs; during my testing I was able to confirm that token renewal - including across refresh token lifetimes - does work in a single tab. I also changed our Keycloak configuration to extend the access token lifetimes, so that this will at least trigger less often.

**Comment by bickelj** [comment]
By extending the access token lifetimes, that means a token can be valid that much longer after a session is over, correct?

**Comment by jasonaowen** [comment]
Yes. Renewing a refresh token already extends the SSO session, and iirc the max session length is like half a day, so a difference of 25 minutes is an increase of ~4%.

**Comment by reefdog** [comment]
@jasonaowen Did any of the recent updates to react-oidc resolve this?

**Comment by jasonaowen** [comment]
No, but mainly because I think this might be a browser issue rather than a library issue. My most recent comment on that issue (which I avoid linking here just to minimize the amount of extraneous activity on that issue) describes how it seems to be working on Chromium 112, although it was still broken on Firefox 112. Nobody else has said anything about being able to reproduce the problem, and I haven't yet tested with Firefox 114.

**Comment by reefdog** [comment]
I haven't run into — or heard of anyone running into — this bug in quite a long time. I'm going to call it "fixed by magic and/or unexpectedly useful entropy" and we can re-open if we find it again.
