### ISSUE TITLE
new nav menu links options, can we target="_blank" them?

### ISSUE THREAD

**Issue by jmergy** [PhilanthropyDataCommons/front-end#595]
@reefdog Just wondering if that was easily doable so it just opens new tabs vs. displacing pdc app site. 

![image](https://github.com/PhilanthropyDataCommons/front-end/assets/2380410/f7988e85-87cc-4d10-ac6e-b14b0e860f62)

Totally minor but asking. I think that would be a good thing to do. For both Developers and About menu items (mailto: link in the mix of course).

Thanks for the consideration.

**Comment by reefdog** [comment]
@jmergy It's definitely _easy_! The question is if we really want that.

In most cases I believe this is an anti-pattern, even with a sensible rule like "only for offsite links". The web is all about linking to resources both within and across domains; in my opinion, the prevalence of new-window-opening links is less about intuiting user intent and more about protecting the origin brand from being forgotten. (Which isn't your thought here, I know, but now I'm riffing on the State of the Industry.)

Browsers let users opt into new tab/window through contextual menu options or modifier clicks; they don't let users opt _out_ of it when the website uses `target=_blank`. We can't actually know which the user wants. My UX preference is to reserve this for only when technically necessary — third-party login/authentication flows? etc. — but otherwise default to staying same-window and let users maintain control over their tab/window management.

Is that convincing? 😆

An exception: `mailto` should absolutely open a new window. As someone who uses an actual application (as opposed to browser-based webmail) for email, I didn't even think about the effect of `mailto` without `target=_blank` on people who use e.g. Gmail, so I didn't test that. I'll check browser behavior for webmail and add `target=_blank` there if it's not automatic.

**Comment by jmergy** [comment]
@reefdog Gotcha. Totally fine with how it works now. Thanks for the rationale on this.

**Comment by jmergy** [comment]
Thank you.
